### ISSUE TITLE
Websocket Relay works for some time but after some time doesn't seem to publish peer-discovery messages

### ISSUE THREAD

**Issue by silkroadnomad** [silkroadnomad/libp2p-relay#3]
After about 1h the WebSocket relay "stops working". 
It accepts new connections from browser peers but doesn't seem to publish peer-discovery messages which results in the symptom that browser peers don't create a swarm.

After restarting the relay everything works again as before. 
Relay runs inside a docker-compose container without persistent volume.

**Comment by silkroadnomad** [comment]
After some minutes already the websocket relay with enabled logging 
shows: "libp2p:gossipsub IHAVE: ignoring peer 12D3Kooxxxxxxxxx with score below threshold [ score = -45 ]"

**Comment by abuvanth** [comment]
yes same issue for me. i am running relay node without docker

**Comment by abuvanth** [comment]
may be the issue is in libp2p lib?

**Comment by abuvanth** [comment]
will check and let you know

**Comment by abuvanth** [comment]
> @abuvanth Yes, its gossip-sub in libp2p.
> 
> I found out during developing, the relay node (libp2p) starts wondering about too many messages from the same IP and then the treshold scores becomes negative! This kicks out all peers as unwanted. (enable DEBUG=libp2p:*) on relay side / and peer see you can watch it!
> 
> In production environment this should not be the case so fast!
> 
> So the solution at the moment is to set the treasholds in libp2p config to negative infinity! At least this is my current solution to it: https://github.com/silkroadnomad/libp2p-relay/blob/main/relay/src/relay.js#L38
> 
> You can just set RELAY_DEV_MODE=true inside .env ? https://github.com/silkroadnomad/libp2p-relay/blob/main/.env.example#L1
> 
> Let me know if it helped.

it works. thanks for this solution

**Comment by silkroadnomad** [comment]
@abuvanth if you want you can have a look a "plain WebRTC" adaptation and fork of the "universal connectivity" example of a libp2p-relay in RUST (!) https://github.com/silkroadnomad/universal-connectivity/tree/main/rust-peer
It works completely with WebRTC only and supports also pub-sub-peer discovery (without any websockets, letsencrypt and nginx)

Also please apologize, I am beginning in RUST and I discovered the relay doesn't do yet circuit-relay as the websocket relay you are using here. This is especially a little annoying in certain Hotels, corporate LANs and sometimes mobile networks too, as they  often block peer-to-peer traffic and sorts.
